---
title: "Species to model Phenology"
author: "steppe"
date: "2024-01-10"
output: html_document
---

```{r}
library(tidyverse)
library(sf)
source('functions.R')
```

```{r import species}

spp <- read.csv('../data/raw/2024species-Priorities.csv') |>
  unite('scientific_name',  genus:infraspecies, na.rm = TRUE, sep = ' ', remove = F) |>
  mutate(
    scientific_name = trimws(scientific_name)) |>
  select(scientific_name, genus, species, contract, priority, priority_source) |>
  count(scientific_name, priority)

```

```{r pull sheets for species and subset to original, eval = F}

specs1 <- lapply(spp$scientific_name, specimen_sampler, 
                 date = '1981-01-01')

specs1 <- specs1[ lapply(specs1, typeof) == 'list' ] |> bind_rows()
# specs1 <- st_read('../data/processed/high_priority_sheets/high_priority_sheets.shp', quiet = TRUE)
specs1 <- mutate(specs1, scntfcn = str_to_sentence(scientificname)) %>% 
  filter(scientificname != 'Chaenactis artemisifolia')
specs1 <- split(specs1, f = specs1$scntfcn)
specs1 <- lapply(specs1, rec_selec)
specs1 <- bind_rows(specs1)

dir.create('../data/processed/high_priority_sheets')
sf::st_write(specs1, '../data/processed/high_priority_sheets/high_priority_sheets.shp', 
             quiet = TRUE, append = F)

rm(specs1)
```

```{r flag records at outer quantiles of flowering, eval = F}

# extract pca values
preds <- rast('../results/spatial/gddPCA.tif')
specs1 <- st_read('../data/processed/high_priority_sheets/high_priority_sheets.shp')

specs1 <- terra::extract(preds, specs1, bind = TRUE) |>
  st_as_sf() %>% 
  drop_na(PC1)

# flag records for manual review. 
specs1 <- split(specs1, f = specs1$scntfcn)
specs1 <- lapply(specs1, visual_review_flagger)
specs2 <- bind_rows(specs1)

priority_spp <- spp %>% 
  filter(priority %in% c('Medium', 'High') | n > 1) %>% 
  pull(scientific_name)

specs2 %>%
  drop_na(phen_flag) %>% 
  sf::st_drop_geometry() %>% 
  filter(scntfcnm %in% priority_spp) %>% 
  select(scntfcnm, accessr, doy) %>% 
  arrange(scntfcnm, doy) %>% 
  mutate(Anthesis = "") #%>% 
 # write.csv( '../data/processed/high_priority_sheets.csv', row.names = F, )

rm(preds, specs2, specs1)

as.Date(206, origin = '1987-01-01')
```

the above records were flagged by visual review of the specimen. During this process, the realization that the check for bimodality should have been performed, and the verification that certain species have many more records outside anthesis, called for a second batch of scoring. 


```{r detect multimodal data}

d <- st_read('../data/processed/high_priority_sheets/high_priority_sheets.shp') %>% 
  mutate(scntfcnm = str_to_sentence(scntfcnm))
splicies <- split(d, f = d$scntfcnm)
ou <- sapply(X = splicies, FUN = function(x){diptest::dip(x$doy) })
ou <- ou[ou < 0.03]
sort(ou, decreasing = TRUE)

modal_finder <- function(x){
  
  dd <- density(x$doy)
  
  vals <- data.frame(
    valu = dd$y[dd$x >= 0 & dd$x <= 366], 
    doy = round(dd$x[dd$x >= 0 & dd$x <= 366], 0)
  )
  
  localMinima <- function(x) { # @ tommy on SO. 
    # Use -Inf instead if x is numeric (non-integer)
    y <- diff(c(.Machine$integer.max, x)) > 0L
    rle(y)$lengths
    y <- cumsum(rle(y)$lengths)
    y <- y[seq.int(1L, length(y), 2L)]
    if (x[[1]] == x[[2]]) {
      y <- y[-1]
    }
    y
  }
  
  localMaxima <- function(x) {
  # Use -Inf instead if x is numeric (non-integer)
   y <- diff(c(-.Machine$integer.max, x)) > 0L
    rle(y)$lengths
    y <- cumsum(rle(y)$lengths)
    y <- y[seq.int(1L, length(y), 2L)]
    if (x[[1]] == x[[2]]) {
      y <- y[-1]
    }
    y
  }
  
  ident_min <- vals$doy[localMinima(vals$valu) ] 
  ident_max <- vals$doy[localMaxima(vals$valu) ] 
  
  v_low <- vals[vals$doy %in% ident_min, ] |>
    dplyr::group_by(doy) |>
    dplyr::slice_sample(n = 1) |>
    dplyr::pull(valu)
  v_high <- vals[vals$doy %in% ident_max, ] |>
    dplyr::group_by(doy) |>
    dplyr::slice_sample(n = 1) |>
    dplyr::pull(valu)

  
  out <- data.frame(
    'DOY' = c(ident_min, ident_max),
    'Value' = c(v_low, v_high), 
    'Variable' =  c(rep('Min', length(ident_min)), rep('Max', length(ident_max))), 
    'prcnt.max' = (c(v_low, v_high) / max(v_high)) * 100
    )  
  
  if(nrow(out[out$Variable == 'Max' & out$prcnt.max >= 10.0, ] > 1)){
    doys <- out[out$Variable == 'Max' & out$prcnt.max >= 10.0, 'DOY']
    min <- out[out$Variable == 'Min' & out$DOY > doys[1] & out$DOY < doys[2],]
    min <- min[ which.min(min$Value), ]
    
    if(min$prcnt.max >= 20.0){min$DOY <- out[ which.min(out$DOY), 'DOY']}
  } 
  
  hist(x = x$doy, main = x$scntfcnm[1], xlab = 'Day of Year', prob = TRUE, 
       ylim = c(0, max(vals$valu)), col = '#F3E9DC', xlim = c(0, 365))
  lines(y = vals$valu, x = vals$doy, lwd = 2)
  abline(v = ident_min , col="#007FFF", lwd = 2, lty = 2) 
  abline(v = ident_max, col = '#590925', lwd = 2, lty = 2)
  abline(v = min$DOY, col = 'red', lwd = 3)

  # if any max peaks are greater than 10%, determine the lowest minimum values between them. 
  return(out)
  return(list(out, min))

}

sapply(X = splicies[11:15], FUN = function(x){diptest::dip(x$doy) }) # 1, 2, 3, 5
ob <- lapply(splicies[34:40], modal_finder)

  hist(x = splicies[[33]]$doy, prob = TRUE)
  lines(density(splicies[[33]]$doy), lwd = 2)


```













```{r}

sheets <- read.csv('../data/processed/high_priority_sheets-scored.csv') 


mode_dat <- filter(sheets, Anthesis == 1) %>% 
  select(scntfcnm, doy)

splicies <- split(sheets, f = sheets$scntfcnm)
splicies <- Filter(function(x) nrow(x)>10, splicies)
# check different methods for identifying multimodal distributions. 

amdu <- filter(sheets, scntfcnm == 'Ambrosia dumosa')



ou <- sapply(X = splicies, FUN =dippeR)

hist(splicies[['Hyptis emoryi']]$doy)

d <- cut(splicies[['Thelesperma megapotamicum']]$doy, breaks = 2)

sort(ou, decreasing = TRUE)
```

